apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-configmap 
  name: nginx-configmap  
spec:
  containers:
  - image: nginx
    name: nginx-configmap
    resources: {}        
    volumeMounts:
    - mountPath: /also/a/path
      name: nginx-configmap-volume
  volumes:
    - name: nginx-configmap-volume
      configMap:
        name: namedanother-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always 