apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  claimRef: # binding to claim
    name: task-pvc-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: storage
  hostPath:
    path: /opt/KDSP00101/data
    type: Directory
