apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: pod-resources
spec:
  resources:
    limits:
      cpu: "200m"
    requests:
      cpu: "200m"
    requests:
      memory: "1Gi"
    limits:
      memory: "1Gi"
  containers:
  - name: nginx-resources
    image: nginx

